version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    restart: always

  minio:
    image: minio/minio:RELEASE.2024-10-02T17-50-41Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    ports:
      - "9033:9000"
      - "9034:9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network
    restart: always

  goapp:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: golang-codebase:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - minio
    working_dir: /opt
    volumes:
      - ../:/opt
    command: ["go", "run", "cmd/app/main.go"]
    networks:
      - app-network
    restart: always

volumes:
  mysql-data:
  minio-data:

networks:
  app-network:
    driver: bridge
